"""Update expenses model

Revision ID: a6fedabe35f0
Revises: b4697d6b0ef3
Create Date: 2026-08-23 20:01:08.029500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fedabe35f0'
down_revision: Union[str, Sequence[str], None] = 'b4697d6b0ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operational_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('incurred_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operational_expenses', schema=None) as batch_op:
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('incurred_date')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
