"""Update SalesOrder for ERP mode

Revision ID: ba65b0f69880
Revises: d182fa3862fe
Create Date: 2026-08-23 21:38:12.879429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba65b0f69880'
down_revision: Union[str, Sequence[str], None] = 'd182fa3862fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sale_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('anticipo', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_column('estimated_delivery_date')
        batch_op.drop_column('anticipo')
        batch_op.drop_column('sale_type')
        batch_op.drop_column('import_date')

    # ### end Alembic commands ###
